### PR TITLE
fix(react/transform): prevent merging JSX elements with dynamic key

### LINKED ISSUE #290: [Bug]: key is not handled properly while snapshotify JSXElement
### System Info

  System:
    OS: Linux 5.15
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.12.0 - /data00~/.local/share/fnm/node-versions/v22.12.0/installation/bin/node
    npm: 10.9.0 - /data00~/.local/share/fnm/node-versions/v22.12.0/installation/bin/npm
    pnpm: 10.6.5 - /data00~/.local/share/fnm/node-versions/v22.12.0/installation/bin/pnpm
  npmPackages:
    @lynx-js/qrcode-rsbuild-plugin: workspace:* => 0.3.4 
    @lynx-js/react: workspace:* => 0.105.2 
    @lynx-js/react-rsbuild-plugin: workspace:* => 0.9.2 
    @lynx-js/rspeedy: workspace:* => 0.8.4 

### Details

An error like below will occur:

```txt
cannot read property 'Symbol.iterator' of undefined backtrace:
    at insertBefore (file://main-thread.js:166:329)
    at snapshotPatchApply (file://main-thread.js:176:269)
    at updatePatch (file://main-thread.js:177:214)
```

### Reproduce link

_No response_

### Reproduce Steps

Create a minimal project with root component like below:

```jsx
import { useState, useEffect } from "@lynx-js/react"

export function App() {
  const [hello, setHello] = useState("Lynx");
  useEffect(() => {
    const id = setTimeout(() => {
      setHello("World")
    }, 1000)
    return () => {
      clearTimeout(id)
    }
  }, [])
  return (
    <view style={{ flexDirection: 'column' }}>
      <text>Hello, ReactLynx 3! Hello, {hello}</text>
      <text key={hello}>{hello}</text>
    </view>
  );
}
```

An error will occur 1 sec later. The root cause of this bug is the `key={hello}`.

A workaround is to wrap `<text key={hello}>{hello}</text>` with `{}`.

If we deep dive down into the transformer, we will see our jsx is transformed:

```jsx
// a snapshot in shape like below:
  <view style={{ flexDirection: 'column' }}>
    <text>Hello, ReactLynx 3! Hello, <wrapper/></text>
    <wrapper/>
  </view>;
```

and

```jsx
/* @__PURE__ */ createVNode2(__snapshot_7a8c6_73078_1, {
    children: [
      /* @__PURE__ */ createVNode2("wrapper", {
        children: hello,
      }),
      /* @__PURE__ */ createVNode2(
        __snapshot_7a8c6_73078_2,
        {
          children: hello,
        },
        hello
      ),
    ],
  })
```

We assumed that `__snapshot_7a8c6_73078_1`'s children will never change, but it will do in this case because of the `key`. So a unexpected `insertBefore` will happen and framework crashs at code below:

Image

To fix this bug, we can add a `wrapper`, the expected transform result can be:

```jsx
/* @__PURE__ */ createVNode2(__snapshot_7a8c6_73078_1, {
    children: [
      /* @__PURE__ */ createVNode2("wrapper", {
        children: hello,
      }),
      /* @__PURE__ */ createVNode2("wrapper", {
        children: /* @__PURE__ */ createVNode2(
            __snapshot_7a8c6_73078_2,
            {
              children: hello,
            },
            hello
          ),
      }),
    ],
  })
```

### PR DESCRIPTION
**Pull request by gaoachao**
## Summary

close #290

- Prevent merging JSX elements with dynamic key attributes by setting `should_merge=false`
- JSX elements with `key={expr}` will now be wrapped with `internal-slot` and `wrapper`

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

### CODE REVIEW

File: packages/react/transform/src/swc_plugin_snapshot/mod.rs [hunk 1]
```diff
@@ -2914,4 +2914,31 @@ mod tests {
...
+      Mark::new(),
+      Mark::new(),
+      TransformMode::Test,
+    )),
+    should_wrap_dynamic_key,
+    // Input codes
+    r#"
+    <view>
+      <text>Hello, ReactLynx, {hello}</text>
+      <text key={hello}>{hello}</text>
```
Comment (upupming) [inline packages/react/transform/src/swc_plugin_snapshot/mod.rs:2940]: Can we also add a test with static key? We should ensure elements with static key can be merged.

File: packages/react/transform/tests/__swc_snapshots__/src/swc_plugin_snapshot/mod.rs/should_wrap_dynamic_key.js [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+    [
+        ReactLynx.__DynamicPartSlot,
+        3
+    ],
+    [
+        ReactLynx.__DynamicPartSlot,
+        4
+    ]
+], undefined, globDynamicComponentEntry);
+<__snapshot_da39a_test_1><wrapper>{hello}</wrapper><wrapper><__snapshot_da39a_test_2 key={hello}>{hello}</__snapshot_da39a_test_2>
```
Comment (upupming) [inline packages/react/transform/tests/__swc_snapshots__/src/swc_plugin_snapshot/mod.rs/should_wrap_dynamic_key.js:51]: Can we eliminate this `<wrapper>` here?

File: packages/react/transform/src/swc_plugin_snapshot/mod.rs (hunk 1 above)
Comment (gaoachao) [reply packages/react/transform/src/swc_plugin_snapshot/mod.rs:2940]: Great catch!
https://github.com/lynx-family/lynx-stack/pull/547/commits/397e7015e191bd241f0ad66944d304630a8cb983

File: .changeset/violet-peas-chew.md [hunk 3]
```diff
@@ -0,0 +1,2 @@
+---
```
Comment (upupming) [inline .changeset/violet-peas-chew.md:1]: We should add changelog to `@lynx-js/react`.

**Review by upupming — DISMISSED** [review]

**Review by hzy — DISMISSED** [review]

**Review by upupming — APPROVED** [review]
